Climatic_Mass_Balance_AIS:
  module: livvext/smb/smb_icecores.py
  References:
    [
      /global/cfs/cdirs/e3sm/livvkit/data/smb/smb_icecores.bib,
      /global/cfs/cdirs/e3sm/livvkit/data/livvkit.bib,
    ]
  meta:
    Case ID: [CASE_ID]
    Climatology years: [1980-2020]
    Model: [E3SM-ELM]
  climo: CASE_OUT_DIR/CASE_ID.{clim}_mean.nc
  climo_remap: CASE_OUT_DIR/remap/CASE_ID.{clim}_mean_rcmais.nc

  latlon: CASE_OUT_DIR/CASE_ID.ANN_mean.nc
  elevation: CASE_OUT_DIR/CASE_ID.ANN_mean.nc
  topo: CASE_OUT_DIR/CASE_ID.ANN_mean.nc
  latv: lat
  lonv: lon
  smbv: QICE
  topov: topo
  landfracv: landfrac
  maskv: ais_mask2
  smbscale: 31536000
  core_year_s: 1980
  core_year_e: 2021
  ib_year_e: 1987-1976
  ib_year_s: 2014-2004
  preprocess: []
  preproc_dir: /global/cfs/cdirs/e3sm/livvkit/data/smb/processed
  dataset_names: { model: ELM, dset_a: RACMO 2.4 }
  clim_years:
    dset_a: { year_s: 1980, year_e: 2020 }
  scales:
    { model: 365 * 24 * 3600, dset_a: 365 * 24 * 3600, dset_b: 365 * 24 * 3600 }
  icesheet: ais
  data_vars: !include config/cmb_vars.yml
  units: mm w. e. yr^-1
  primary_var: Climatic Mass Balance
  vars:
    {
      rain: RAIN,
      snow: SNOW,
      melt: QICE_MELT,
      runoff: QRUNOFF,
      freeze: QICE_FRZ,
    }
  in_dirs: { dset_a: "/global/cfs/cdirs/fanssie/racmo/2.4.1/clm/{_var}" }
  file_patterns:
    { dset_a: "{_var}_{icesheet}_{season}_{sea_s}_{sea_e}_climo.nc" }
  timeseries_dirs:
    {
      model: "/global/cfs/projectdirs/e3sm/zender/livvkit",
      dset_a: "/global/cfs/cdirs/fanssie/racmo/2.4.1/ts",
    }
  ts_file_patterns:
    {
      model: "CASE_ID.nc",
      dset_a: "{_var}_{icesheet}_{year_s}01_{year_e}12.nc",
    }
  masks:
    {
      dset_a: /global/cfs/cdirs/e3sm/zender/grids/msk_ais_r025_rcm.nc,
      model: /global/cfs/cdirs/e3sm/zender/grids/msk_ais_r025_rcm.nc,
      model_native: /global/cfs/cdirs/e3sm/livvkit/grids/msk_ais_rcm_r05.nc,
    }
  desc: "{component} component of CMB from {data_var_names}"
  cmap: BrBG
  cmap_diff: BrBG
  clim_even: 1
