Climatic_Mass_Balance_AIS:
  module: livvext/smb/smb_icecores.py
  References: [/global/cfs/cdirs/e3sm/livvkit/data/smb/smb_icecores.bib,/global/cfs/cdirs/e3sm/livvkit/data/livvkit.bib]
  meta:
    Case ID: [v2.1.r05.BGWCYCL20TR-steve_2005_2014]
    Climatology years: [1980-2020]
    Model: [E3SM-ELM]
  climo: /pscratch/sd/m/mek/livvext/data/e3sm/v2.1.r05.BGWCYCL20TR-steve_2005_2014/v2.1.r05.BGWCYCL20TR-steve_2005_2014.{clim}_mean.nc
  climo_remap: /pscratch/sd/m/mek/livvext/data/e3sm/v2.1.r05.BGWCYCL20TR-steve_2005_2014/remap/v2.1.r05.BGWCYCL20TR-steve_2005_2014.{clim}_mean_rcmais.nc
  aavg: /global/cfs/cdirs/e3sm/livvkit/data/e3sm/lnd/20240524.IGELM_MLI.ne30pg2_r05_IcoswISC30E3r5_gis10to10r02.pm-cpu.gnu.1k_spin_1990_2022_{clim}_1990{m_s:02d}_2021{m_e:02d}_climo_gis_mask2_aavg.nc
  latlon: /pscratch/sd/m/mek/livvext/data/e3sm/v2.1.r05.BGWCYCL20TR-steve_2005_2014/v2.1.r05.BGWCYCL20TR-steve_2005_2014.ANN_mean.nc
  elevation: /pscratch/sd/m/mek/livvext/data/e3sm/v2.1.r05.BGWCYCL20TR-steve_2005_2014/v2.1.r05.BGWCYCL20TR-steve_2005_2014.ANN_mean.nc
  topo: /pscratch/sd/m/mek/livvext/data/e3sm/v2.1.r05.BGWCYCL20TR-steve_2005_2014/v2.1.r05.BGWCYCL20TR-steve_2005_2014.ANN_mean.nc
  latv: lat
  lonv: lon
  smbv: QICE
  topov: topo
  landfracv: landfrac
  maskv: ais_mask2
  smbscale: 31536000
  preprocess: []
  preproc_dir: /global/cfs/cdirs/e3sm/livvkit/data/smb/processed
  racmo_dir: /pscratch/sd/m/mek/livvext/data/racmo_2p4p1/remapped/climo
  racmo_dir_native: /pscratch/sd/m/mek/livvext/data/racmo_2p4p1/climo
  racmo_ver: "2.4"
  dataset_names: { model: ELM, dset_a: RACMO 2.4 }
  clim_years:
    dset_a: { year_s: 1980, year_e: 2020 }
  scales:
    { model: 365 * 24 * 3600, dset_a: 365 * 24 * 3600, dset_b: 365 * 24 * 3600 }
  icesheet: ais
  data_vars: !include config/cmb_vars.yml
  units: mm w. e. yr^-1
  primary_var: Climatic Mass Balance
  vars:
    {
      rain: RAIN,
      snow: SNOW,
      melt: QICE_MELT,
      runoff: QRUNOFF,
      freeze: QICE_FRZ,
    }
  in_dirs: { dset_a: "/global/cfs/cdirs/fanssie/racmo/2.4.1/clm/{_var}" }
  file_patterns:
    { dset_a: "{_var}_{icesheet}_{season}_{sea_s}_{sea_e}_climo.nc" }
  timeseries_dirs:
    {
      model: "/global/cfs/projectdirs/e3sm/zender/livvkit",
      dset_a: "/global/cfs/cdirs/fanssie/racmo/2.4.1/ts",
    }
  ts_file_patterns:
    {
      model: "v2.1.r05.BGWCYCL20TR-steve_2005_2014.nc",
      dset_a: "{_var}_{icesheet}_{year_s}01_{year_e}12.nc",
    }
  masks:
    {
      dset_a: /global/cfs/cdirs/e3sm/zender/grids/msk_ais_r025_rcm.nc,
      model: /global/cfs/cdirs/e3sm/zender/grids/msk_ais_r025_rcm.nc,
      model_native: /pscratch/sd/m/mek/livvext/data/grids/msk_ais_rcm_r05.nc,
    }
  desc: "{component} component of CMB from {data_var_names}"
  cmap: BrBG
  cmap_diff: BrBG
  clim_even: 1
