Energy_Balance_CERES_AIS:
  module: livvext/energy/energy.py
  references: [/global/cfs/cdirs/e3sm/livvkit/data/racmo/Noel2015.bib,/global/cfs/cdirs/e3sm/livvkit/data/cism/glissade/cism-glissade.bib,/global/cfs/cdirs/e3sm/livvkit/data/e3sm/Evans2019.bib,
   /global/cfs/cdirs/e3sm/livvkit/data/livvkit.bib]
  meta:
    Case ID: [v3.LR.piControl.I.hex_eqm_0001_0100]
    Climatology years: [1980-2020]
    Model: [E3SM-ELM]
  img_height: 300
  climo: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/v3.LR.piControl.I.hex_eqm_0001_0100.{clim}_mean.nc
  climo_remap: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/remap/v3.LR.piControl.I.hex_eqm_0001_0100.{clim}_mean_cmip6.nc
  lnd_climo: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/v3.LR.piControl.I.hex_eqm_0001_0100.ANN_mean.nc
  glc_surf: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/v3.LR.piControl.I.hex_eqm_0001_0100.ANN_mean.nc
  aavg: /global/cfs/cdirs/e3sm/livvkit/data/e3sm/lnd/20240524.IGELM_MLI.ne30pg2_r05_IcoswISC30E3r5_gis1to10r02.pm-cpu.gnu.1k_spin_1990_2022_{clim}_1990{m_s:02d}_2021{m_e:02d}_climo_gis_mask2_aavg.nc
  latlon: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/v3.LR.piControl.I.hex_eqm_0001_0100.ANN_mean.nc
  elevation: /pscratch/sd/m/mek/livvext/data/e3sm/v3.LR.piControl.I.hex_eqm_0001_0100/v3.LR.piControl.I.hex_eqm_0001_0100.ANN_mean.nc
  latv: lat
  lonv: lon
  topov: topo
  landfracv: landfrac
  icesheet: ais
  maskv: gis_mask2
  dataset_names: {model_native: ELM, model_remap: 'ELM [CERES Grid]', dset_a: CERES}
  aavg_sort: [ELM, 'ELM [CERES Grid]', CERES]
  mask_ocean: {model_native: false, model_remap: true, dset_a: true}
  scales: {model: 1, dset_a: 1}
  data_vars:
  - title: Albedo
    dset_a: [/, rsus, rsds]
    model:
    - /
    - [+, FSRND, FSRVD]
    - [+, FSDSVD, FSDSND]
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: unitless
  - dset_a: sfc_net_sw_all_mon
    model: FSA
    title: Shortwave net
    comment: ' (Positive to surface)'
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: rsds
    model: FSDS
    title: Shortwave down
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  - dset_a: sfc_net_lw_all_mon
    model: FIRA
    title: Longwave net
    comment: ' (Positive to atmosphere)'
    sign: 1
    scales: {dset_a: -1, model: 1}
    units: W m^-2
  - dset_a: rlds
    model: FLDS
    title: Longwave down
    sign: 1
    scales: {dset_a: 1, model: 1}
    units: W m^-2
  in_dirs: {dset_a: /pscratch/sd/m/mek/livvext/data/ceres_ebaf_surface_v4.1}
  file_patterns: {dset_a: 'ceres_ebaf_surface_v4.1_{season}_climo.nc'}
  masks: {dset_a: /pscratch/sd/m/mek/livvext/data/grids/msk_ais_rcm_r025_regrid_cmip6_traave_20250310.nc,
    model_native: /global/cfs/cdirs/e3sm/zender/grids/msk_ais_rcm_r05.nc, model_remap: /pscratch/sd/m/mek/livvext/data/grids/msk_ais_rcm_r025_regrid_cmip6_traave_20250310.nc}
  desc: Surface energy balance component {component}{comment} from {data_var_names}
  cmap: plasma
  cmap_diff: RdBu_r
