# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.10"
            pixi-env: py310dev
          - python-version: "3.11"
            pixi-env: py311dev
          - python-version: "3.12"
            pixi-env: py312dev
          - python-version: "3.13"
            pixi-env: py313dev
          - python-version: "3.14"
            pixi-env: py314dev

    steps:
    - uses: actions/checkout@v6
    - name: Set up Pixi ${{ matrix.python-version }}
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        pixi-version: v0.62.2
        # Project environment caching uses pixi.lock as the cache key input.
        # If you don't commit a lockfile, disable caching to avoid ENOENT.
        # cache: ${{ hashFiles('pixi.lock') != '' }}
        environments: ${{ matrix.pixi-env }}
    - name: Run tests
      run: |
        pixi run -e ${{ matrix.pixi-env }} pytest -vvv
